[workspace]
authors = ["Tomáš Kysela <tomkys144@gmail.com>"]
channels = ["conda-forge"]
name = "NetSci Project"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
run = "python main.py $PIXI_PROJECT_ROOT"

[dependencies]
numpy = ">=2.3.5,<3"
pandas = ">=2.3.3,<3"
networkx = ">=3.6.1,<4"
python = ">=3.14.2,<3.15"
matplotlib = ">=3.10.8,<4"
graph-tool = ">=2.98,<3"
pyright = ">=1.1.407,<2"
librsvg = ">=2.60.0,<3"

[feature.pycharm-dev.dependencies]
pixi-pycharm = ">=0.0.10,<0.0.11"

[environments]
pycharm-dev = ["pycharm-dev"]
